"""Evidence graph contracts, ingestion, and local engine utilities."""

from pmem.graph.benchmark import (
    DEFAULT_BENCHMARK_ITERATIONS,
    DEFAULT_BENCHMARK_SIZES,
    MIGRATION_DECISION_NODE_COUNT,
    NEO4J_MIGRATION_THRESHOLD_SECONDS,
    NETWORKX_BENCHMARK_METHOD,
    GraphQueryBenchmarkResult,
    Neo4jMigrationGateResult,
    run_networkx_query_benchmark,
    synthetic_query_benchmark_document,
)
from pmem.graph.engine import GRAPH_ENGINE_METHOD, GraphEngine
from pmem.graph.incremental import (
    BUILD_MODE_FULL,
    BUILD_MODE_INCREMENTAL_FALLBACK_FULL,
    BUILD_MODE_INCREMENTAL_NOOP,
    GRAPH_INCREMENTAL_METHOD,
    GraphBuildResult,
    GraphSourceFingerprint,
    build_graph_full,
    build_graph_incremental,
    compute_graph_source_fingerprint,
)
from pmem.graph.ingestion import (
    GRAPH_INGESTION_METHOD,
    GraphDocument,
    GraphEdge,
    GraphNode,
    build_graph_from_database,
    build_graph_from_project,
)
from pmem.graph.lineage import (
    GRAPH_LINEAGE_METHOD,
    GraphLineageService,
    LineageHop,
    RunLineage,
)
from pmem.graph.persistence import (
    default_graph_artifact_path,
    read_graph_document,
    write_graph_document,
)
from pmem.graph.privacy import graph_artifact_policy
from pmem.graph.provenance import GraphProvenance
from pmem.graph.query import (
    GRAPH_QUERY_METHOD,
    GraphNeighbor,
    GraphPath,
    GraphQueryService,
    GraphSubgraph,
)
from pmem.graph.schema import (
    EDGE_SPECS,
    GRAPH_SCHEMA_VERSION,
    NODE_TYPES,
    EdgeClass,
    EdgeSpec,
    EdgeType,
    NodeType,
    canonical_schema_json,
    code_module_node_id,
    edge_id,
    graph_schema_document,
    is_supported_metric_value,
)

__all__ = [
    "EDGE_SPECS",
    "GRAPH_SCHEMA_VERSION",
    "NODE_TYPES",
    "EdgeClass",
    "EdgeSpec",
    "EdgeType",
    "GRAPH_ENGINE_METHOD",
    "NETWORKX_BENCHMARK_METHOD",
    "MIGRATION_DECISION_NODE_COUNT",
    "DEFAULT_BENCHMARK_ITERATIONS",
    "DEFAULT_BENCHMARK_SIZES",
    "NEO4J_MIGRATION_THRESHOLD_SECONDS",
    "GRAPH_INGESTION_METHOD",
    "GRAPH_INCREMENTAL_METHOD",
    "GRAPH_LINEAGE_METHOD",
    "GRAPH_QUERY_METHOD",
    "GraphEngine",
    "GraphQueryBenchmarkResult",
    "GraphBuildResult",
    "GraphSourceFingerprint",
    "GraphLineageService",
    "GraphNeighbor",
    "GraphPath",
    "GraphProvenance",
    "GraphQueryService",
    "GraphSubgraph",
    "GraphDocument",
    "GraphEdge",
    "GraphNode",
    "LineageHop",
    "NodeType",
    "Neo4jMigrationGateResult",
    "RunLineage",
    "build_graph_from_database",
    "build_graph_from_project",
    "build_graph_full",
    "build_graph_incremental",
    "canonical_schema_json",
    "code_module_node_id",
    "compute_graph_source_fingerprint",
    "default_graph_artifact_path",
    "edge_id",
    "graph_artifact_policy",
    "graph_schema_document",
    "is_supported_metric_value",
    "read_graph_document",
    "run_networkx_query_benchmark",
    "synthetic_query_benchmark_document",
    "write_graph_document",
    "BUILD_MODE_FULL",
    "BUILD_MODE_INCREMENTAL_FALLBACK_FULL",
    "BUILD_MODE_INCREMENTAL_NOOP",
]
